services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_USERNAME=aaron
      - MONGO_INITDB_PASSWORD=aaron
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aaron
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aaron
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}